/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetpanneaupub;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import passInfo.Donnee;

/**
 *
 * @author AMEGNITO Brice
 */
public class Acceuil extends javax.swing.JFrame {
 public String PersonTyp ;
    /**
     * Creates new form Acceuil
     */
    Color DefaulColor,ClickColor;
    public Acceuil() {
        initComponents();
        Affiche();
        Info();
        DefaulColor= new Color(51,153,255);
        ClickColor= new Color(000,000,000);
        
        ClientPane.setBackground(DefaulColor);
        PaneauPane.setBackground(DefaulColor);
        AbonPane.setBackground(DefaulColor);
        RecherchePane.setBackground(DefaulColor);
        
         // Visibilité des fenetre:
       FenClient.setVisible(false);
       FenAbonnement3.setVisible(false);
       FenPanneau.setVisible(false);
    }
     public void Info(){
        lblUserCon.setText(Donnee.getNomPersonnel());
        lblTypePers.setText(Donnee.getTypePersonnel());
        PersonTyp =Donnee.getTypePersonnel();
    }
    
    public void Affiche(){
        try {
            String donnee []={"Identifiant","Nom","Adresse","Téléphone"};
            DefaultTableModel model=new DefaultTableModel(null,donnee);
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
            prst1=connect.prepareStatement("SELECT * FROM  client ");
            rsl=prst1.executeQuery();
            while(rsl.next()){
                Object ob[]={
                    rsl.getString("Id_Client"),
                    rsl.getString("Nom_Client"),
                    rsl.getString("Adresse_Client"),
                    rsl.getString("Tel_Client")
                };
                model.addRow(ob);
            }
            TableClient1.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(panneaux.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     Connection connect ;
    PreparedStatement prst,prst1;
     ResultSet rsl;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAdrCli = new javax.swing.JTextField();
        txtTelCli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNomCl = new javax.swing.JTextField();
        AjoutBtn = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ModifierBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableClient = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        EnteteTitre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblUserCon = new javax.swing.JLabel();
        lblTypePers = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ClientPane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PaneauPane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        AbonPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        RecherchePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LesFenetres = new javax.swing.JPanel();
        FenClient = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAdrCli1 = new javax.swing.JTextField();
        txtTelCli1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNomCl1 = new javax.swing.JTextField();
        AjoutBtnCli = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        ModifierBtn2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableClient1 = new javax.swing.JTable();
        FenAbonnement3 = new javax.swing.JPanel();
        FenPanneau = new javax.swing.JPanel();

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Adresse");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Téléphone");

        txtTelCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelCliKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Nom Client");

        txtNomCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomClActionPerformed(evt);
            }
        });

        AjoutBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AjoutBtn.setText("Ajouter");
        AjoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutBtnActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(0, 204, 255));
        jPanel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ENREGISTRMENT CLIENT");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        ModifierBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ModifierBtn.setText("Modifier");
        ModifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierBtnActionPerformed(evt);
            }
        });

        TableClient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom Client", "Téléphone", "Location", ""
            }
        ));
        TableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableClient);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(AjoutBtn))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(ModifierBtn))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(txtNomCl, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(txtAdrCli, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomCl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAdrCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTelCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setName("Acceuil"); // NOI18N
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        EnteteTitre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        EnteteTitre.setText("Bienvenu a la CCP");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Utilisateur Connect:");

        lblUserCon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        lblTypePers.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("En tant que :");

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Se Déconnectre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUserCon, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTypePers, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EnteteTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(EnteteTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblUserCon, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(lblTypePers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        ClientPane.setBackground(new java.awt.Color(51, 153, 255));
        ClientPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClientPaneMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Client");

        javax.swing.GroupLayout ClientPaneLayout = new javax.swing.GroupLayout(ClientPane);
        ClientPane.setLayout(ClientPaneLayout);
        ClientPaneLayout.setHorizontalGroup(
            ClientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientPaneLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClientPaneLayout.setVerticalGroup(
            ClientPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        PaneauPane.setBackground(new java.awt.Color(51, 153, 255));
        PaneauPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaneauPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PaneauPaneMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Panneau ");

        javax.swing.GroupLayout PaneauPaneLayout = new javax.swing.GroupLayout(PaneauPane);
        PaneauPane.setLayout(PaneauPaneLayout);
        PaneauPaneLayout.setHorizontalGroup(
            PaneauPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneauPaneLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PaneauPaneLayout.setVerticalGroup(
            PaneauPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneauPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        AbonPane.setBackground(new java.awt.Color(51, 153, 255));
        AbonPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbonPaneMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AbonPaneMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Abonnement");

        javax.swing.GroupLayout AbonPaneLayout = new javax.swing.GroupLayout(AbonPane);
        AbonPane.setLayout(AbonPaneLayout);
        AbonPaneLayout.setHorizontalGroup(
            AbonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbonPaneLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        AbonPaneLayout.setVerticalGroup(
            AbonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbonPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        RecherchePane.setBackground(new java.awt.Color(51, 153, 255));
        RecherchePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RecherchePaneMousePressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recherche");

        javax.swing.GroupLayout RecherchePaneLayout = new javax.swing.GroupLayout(RecherchePane);
        RecherchePane.setLayout(RecherchePaneLayout);
        RecherchePaneLayout.setHorizontalGroup(
            RecherchePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecherchePaneLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RecherchePaneLayout.setVerticalGroup(
            RecherchePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecherchePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClientPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PaneauPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AbonPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RecherchePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ClientPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(PaneauPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(AbonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(RecherchePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FenClient.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Adresse");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Téléphone");

        txtTelCli1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelCli1KeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Nom Client");

        txtNomCl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomCl1ActionPerformed(evt);
            }
        });

        AjoutBtnCli.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AjoutBtnCli.setText("Ajouter");
        AjoutBtnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutBtnCliActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(0, 204, 255));
        jPanel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("ENREGISTRMENT CLIENT");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel31)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        ModifierBtn2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ModifierBtn2.setText("Modifier");
        ModifierBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierBtn2ActionPerformed(evt);
            }
        });

        TableClient1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TableClient1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom Client", "Téléphone", "Location", ""
            }
        ));
        TableClient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClient1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableClient1);

        javax.swing.GroupLayout FenClientLayout = new javax.swing.GroupLayout(FenClient);
        FenClient.setLayout(FenClientLayout);
        FenClientLayout.setHorizontalGroup(
            FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FenClientLayout.createSequentialGroup()
                .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FenClientLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FenClientLayout.createSequentialGroup()
                                .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(FenClientLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(AjoutBtnCli))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FenClientLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(ModifierBtn2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FenClientLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelCli1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(FenClientLayout.createSequentialGroup()
                                .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FenClientLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(txtNomCl1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FenClientLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(txtAdrCli1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FenClientLayout.setVerticalGroup(
            FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
            .addGroup(FenClientLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNomCl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtAdrCli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTelCli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(FenClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjoutBtnCli, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifierBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout FenAbonnement3Layout = new javax.swing.GroupLayout(FenAbonnement3);
        FenAbonnement3.setLayout(FenAbonnement3Layout);
        FenAbonnement3Layout.setHorizontalGroup(
            FenAbonnement3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        FenAbonnement3Layout.setVerticalGroup(
            FenAbonnement3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout FenPanneauLayout = new javax.swing.GroupLayout(FenPanneau);
        FenPanneau.setLayout(FenPanneauLayout);
        FenPanneauLayout.setHorizontalGroup(
            FenPanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        FenPanneauLayout.setVerticalGroup(
            FenPanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LesFenetresLayout = new javax.swing.GroupLayout(LesFenetres);
        LesFenetres.setLayout(LesFenetresLayout);
        LesFenetresLayout.setHorizontalGroup(
            LesFenetresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LesFenetresLayout.createSequentialGroup()
                .addComponent(FenAbonnement3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(LesFenetresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LesFenetresLayout.createSequentialGroup()
                    .addComponent(FenClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 46, Short.MAX_VALUE)))
            .addGroup(LesFenetresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LesFenetresLayout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(FenPanneau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        LesFenetresLayout.setVerticalGroup(
            LesFenetresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LesFenetresLayout.createSequentialGroup()
                .addComponent(FenAbonnement3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(LesFenetresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LesFenetresLayout.createSequentialGroup()
                    .addComponent(FenClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 4, Short.MAX_VALUE)))
            .addGroup(LesFenetresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LesFenetresLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(FenPanneau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LesFenetres, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LesFenetres, javax.swing.GroupLayout.PREFERRED_SIZE, 444, Short.MAX_VALUE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClientPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientPaneMouseClicked
        // TODO add your handling code here:
        FenClient.setVisible(true);
        FenAbonnement3.setVisible(false);
        FenPanneau.setVisible(false);
    }//GEN-LAST:event_ClientPaneMouseClicked

    private void ClientPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientPaneMousePressed
        // TODO add your handling code here:
        ClientPane.setBackground(ClickColor);
        PaneauPane.setBackground(DefaulColor);
        AbonPane.setBackground(DefaulColor);
        RecherchePane.setBackground(DefaulColor);

        EnteteTitre.setText("Enrégistremnt Client");
    }//GEN-LAST:event_ClientPaneMousePressed

    private void PaneauPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneauPaneMouseClicked
        // TODO add your handling code here:
        FenClient.setVisible(false);
        FenAbonnement3.setVisible(false);
        FenPanneau.setVisible(true);
    }//GEN-LAST:event_PaneauPaneMouseClicked

    private void PaneauPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaneauPaneMousePressed
        // TODO add your handling code here:
        ClientPane.setBackground(DefaulColor);
        PaneauPane.setBackground(ClickColor);
        AbonPane.setBackground(DefaulColor);
        RecherchePane.setBackground(DefaulColor);

        EnteteTitre.setText("Enrégistremnt Panneau");
    }//GEN-LAST:event_PaneauPaneMousePressed

    private void AbonPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbonPaneMouseClicked
        // TODO add your handling code here:
        FenClient.setVisible(false);
        FenAbonnement3.setVisible(true);
        FenPanneau.setVisible(false);
    }//GEN-LAST:event_AbonPaneMouseClicked

    private void AbonPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbonPaneMousePressed
        // TODO add your handling code here:
        ClientPane.setBackground(DefaulColor);
        PaneauPane.setBackground(DefaulColor);
        AbonPane.setBackground(ClickColor);
        RecherchePane.setBackground(DefaulColor);

        EnteteTitre.setText("Enrégistremnt Abonnement");
    }//GEN-LAST:event_AbonPaneMousePressed

    private void RecherchePaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecherchePaneMousePressed
        // TODO add your handling code here:
        ClientPane.setBackground(DefaulColor);
        PaneauPane.setBackground(DefaulColor);
        AbonPane.setBackground(DefaulColor);
        RecherchePane.setBackground(ClickColor);

        EnteteTitre.setText("Faure une recherche");
    }//GEN-LAST:event_RecherchePaneMousePressed

    private void txtTelCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelCliKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            txtTelCli.setEditable(false);
        }else{
            txtTelCli.setEditable(true);
        }
    }//GEN-LAST:event_txtTelCliKeyPressed

    private void txtNomClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomClActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomClActionPerformed

    private void AjoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutBtnActionPerformed
        String reg_paternes= "^[A-Za-z0-9]$";
        Pattern patte = Pattern.compile(reg_paternes);
        Matcher match =patte.matcher(txtNomCl1.getText());
        String NomCl = txtNomCl1.getText();
        String AdrCli = txtAdrCli.getText();
        String TelCli = txtTelCli.getText();
        if(NomCl.equals("")||AdrCli.equals("")||TelCli.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir Tous les champs");
        }else if(!match.matches()){
            JOptionPane.showMessageDialog(null, "Veuillez saisir un valide");

        }else{

            try {
                // TODO add your handling code here:

                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
                    prst1=connect.prepareStatement("SELECT * FROM   client WHERE Tel_Client=? ");
                    prst1.setString(1, TelCli);

                    rsl=prst1.executeQuery();
                    if(rsl.next()){
                        JOptionPane.showMessageDialog(this, "Ce panneau est déja! enrégistrer");
                    }else{
                        try {

                            prst = connect.prepareStatement("INSERT INTO  client(Nom_Client,Adresse_Client,Tel_Client) VALUES(?,?,?)");
                            prst.setString(1, NomCl);
                            prst.setString(2,AdrCli);
                            prst.setString(3,TelCli);
                            prst.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Panneau ajouté!");
                            txtNomCl.setText("");
                            txtAdrCli.setText("");
                            txtTelCli.setText("");

                        } catch (SQLException ex) {
                            Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                        }                     }
                    } catch (SQLException ex) {
                        Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                }
                Affiche();
            }
    }//GEN-LAST:event_AjoutBtnActionPerformed

    private void ModifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBtnActionPerformed
        // TODO add your handling code here:
        String NomCl = txtNomCl.getText();
        String AdrCli = txtAdrCli.getText();
        String TelCli = txtTelCli.getText();
        if(NomCl.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez Clicker l'élément à modifier");
        } else{
            DefaultTableModel mod =new DefaultTableModel();
            mod =(DefaultTableModel)TableClient1.getModel();
            int select = TableClient1.getSelectedRow();
            int id = Integer.parseInt(mod.getValueAt(select, 0).toString());

            // TODO add your handling code here:

            /*try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
                prst1=connect.prepareStatement("SELECT * FROM  panneau WHERE Localisation_panneau=?,Taille=?, Prix=?  ");
                prst1.setString(1, localisation);
                prst1.setString(2,taille);
                prst1.setString(3,prix);
                rsl=prst1.executeQuery();
                if(rsl.next()){
                    JOptionPane.showMessageDialog(this, "Ce panneau est déja! enrégistrer");
                }else{*/

                    try {

                        prst = connect.prepareStatement("UPDATE client SET Nom_Client=?, Adresse_Client=?, Tel_Client=? WHERE Id_Client =?");
                        prst.setString(1, NomCl);
                        prst.setString(2,AdrCli);
                        prst.setString(3,TelCli);
                        prst.setInt(4,id);
                        prst.executeUpdate();
                        JOptionPane.showMessageDialog(this, " Modifier!");
                        txtNomCl.setText("");
                        txtAdrCli.setText("");
                        txtTelCli.setText("");

                    } catch (SQLException ex) {
                        Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    /*}
            } catch (Exception e) {
                Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, e);
            } */

            Affiche();
            AjoutBtnCli.setEnabled(true);
        }
    }//GEN-LAST:event_ModifierBtnActionPerformed

    private void TableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClientMouseClicked
        // TODO add your handling code here:
        DefaultTableModel mod =new DefaultTableModel();
        mod =(DefaultTableModel)TableClient1.getModel();
        int select = TableClient1.getSelectedRow();
        int id = Integer.parseInt(mod.getValueAt(select, 0).toString());
        txtNomCl.setText(mod.getValueAt(select, 1).toString());
        txtAdrCli.setText(mod.getValueAt(select, 2).toString());
        txtTelCli.setText(mod.getValueAt(select, 3).toString());
        AjoutBtnCli.setEnabled(false);
    }//GEN-LAST:event_TableClientMouseClicked

    private void txtTelCli1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelCli1KeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            txtTelCli1.setEditable(false);
        }else{
            txtTelCli1.setEditable(true);
        }
    }//GEN-LAST:event_txtTelCli1KeyPressed

    private void txtNomCl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomCl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomCl1ActionPerformed

    private void AjoutBtnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutBtnCliActionPerformed
        String reg_paternes= "^[A-Za-z0-9]$";
        Pattern patte = Pattern.compile(reg_paternes);
        Matcher match =patte.matcher(txtNomCl1.getText());
        String NomCl = txtNomCl1.getText();
        String AdrCli = txtAdrCli1.getText();
        String TelCli = txtTelCli1.getText();
        if(NomCl.equals("")||AdrCli.equals("")||TelCli.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir Tous les champs");
        }else if(!match.matches()){
            JOptionPane.showMessageDialog(null, "Veuillez saisir un valide");

        }else{

            try {
                // TODO add your handling code here:

                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
                    prst1=connect.prepareStatement("SELECT * FROM   client WHERE Tel_Client=? ");
                    prst1.setString(1, TelCli);

                    rsl=prst1.executeQuery();
                    if(rsl.next()){
                        JOptionPane.showMessageDialog(this, "Ce panneau est déja! enrégistrer");
                    }else{
                        try {

                            prst = connect.prepareStatement("INSERT INTO  client(Nom_Client,Adresse_Client,Tel_Client) VALUES(?,?,?)");
                            prst.setString(1, NomCl);
                            prst.setString(2,AdrCli);
                            prst.setString(3,TelCli);
                            prst.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Panneau ajouté!");
                            txtNomCl1.setText("");
                            txtAdrCli1.setText("");
                            txtTelCli1.setText("");

                        } catch (SQLException ex) {
                            Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                        }                     }
                    } catch (SQLException ex) {
                        Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                }
                Affiche();
            }
    }//GEN-LAST:event_AjoutBtnCliActionPerformed

    private void ModifierBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBtn2ActionPerformed
        // TODO add your handling code here:
        String NomCl = txtNomCl1.getText();
        String AdrCli = txtAdrCli1.getText();
        String TelCli = txtTelCli1.getText();
        if(NomCl.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez Clicker l'élément à modifier");
        } else{
            DefaultTableModel mod =new DefaultTableModel();
            mod =(DefaultTableModel)TableClient1.getModel();
            int select = TableClient1.getSelectedRow();
            int id = Integer.parseInt(mod.getValueAt(select, 0).toString());

            // TODO add your handling code here:

            /*try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
                prst1=connect.prepareStatement("SELECT * FROM  panneau WHERE Localisation_panneau=?,Taille=?, Prix=?  ");
                prst1.setString(1, localisation);
                prst1.setString(2,taille);
                prst1.setString(3,prix);
                rsl=prst1.executeQuery();
                if(rsl.next()){
                    JOptionPane.showMessageDialog(this, "Ce panneau est déja! enrégistrer");
                }else{*/

                    try {

                        prst = connect.prepareStatement("UPDATE client SET Nom_Client=?, Adresse_Client=?, Tel_Client=? WHERE Id_Client =?");
                        prst.setString(1, NomCl);
                        prst.setString(2,AdrCli);
                        prst.setString(3,TelCli);
                        prst.setInt(4,id);
                        prst.executeUpdate();
                        JOptionPane.showMessageDialog(this, " Modifier!");
                        txtNomCl1.setText("");
                        txtAdrCli1.setText("");
                        txtTelCli1.setText("");

                    } catch (SQLException ex) {
                        Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    /*}
            } catch (Exception e) {
                Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, e);
            } */

            Affiche();
            AjoutBtnCli.setEnabled(true);
        }
    }//GEN-LAST:event_ModifierBtn2ActionPerformed

    private void TableClient1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClient1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel mod =new DefaultTableModel();
        mod =(DefaultTableModel)TableClient1.getModel();
        int select = TableClient1.getSelectedRow();
        int id = Integer.parseInt(mod.getValueAt(select, 0).toString());
        txtNomCl1.setText(mod.getValueAt(select, 1).toString());
        txtAdrCli1.setText(mod.getValueAt(select, 2).toString());
        txtTelCli1.setText(mod.getValueAt(select, 3).toString());
        AjoutBtnCli.setEnabled(false);
    }//GEN-LAST:event_TableClient1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PrincipalAccueil().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceuil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceuil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbonPane;
    private javax.swing.JButton AjoutBtn;
    private javax.swing.JButton AjoutBtnCli;
    private javax.swing.JButton AjoutBtnUti;
    private javax.swing.JButton AjoutBtnUti1;
    private javax.swing.JButton AjoutBtnUti2;
    private javax.swing.JPanel ClientPane;
    private javax.swing.JLabel EnteteTitre;
    private javax.swing.JPanel FenAbonnement;
    private javax.swing.JPanel FenAbonnement1;
    private javax.swing.JPanel FenAbonnement2;
    private javax.swing.JPanel FenAbonnement3;
    private javax.swing.JPanel FenClient;
    private javax.swing.JPanel FenPanneau;
    private javax.swing.JPanel FenUtilisateur;
    private javax.swing.JPanel FenUtilisateur1;
    private javax.swing.JPanel FenUtilisateur2;
    private javax.swing.JPanel LesFenetres;
    private javax.swing.JButton ModifierBtn;
    private javax.swing.JButton ModifierBtn2;
    private javax.swing.JPanel PaneauPane;
    private javax.swing.JPanel RecherchePane;
    private javax.swing.JTable TableClient;
    private javax.swing.JTable TableClient1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTypePers;
    private javax.swing.JLabel lblUserCon;
    private javax.swing.JTextField txtAdrCli;
    private javax.swing.JTextField txtAdrCli1;
    private javax.swing.JTextField txtNomCl;
    private javax.swing.JTextField txtNomCl1;
    private javax.swing.JTextField txtTelCli;
    private javax.swing.JTextField txtTelCli1;
    private javax.swing.JTextField txtUserPass;
    private javax.swing.JTextField txtUserPass1;
    private javax.swing.JTextField txtUserPass2;
    private javax.swing.JTextField txtUserTel;
    private javax.swing.JTextField txtUserTel1;
    private javax.swing.JTextField txtUserTel2;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    private javax.swing.JTextField txtUsername2;
    // End of variables declaration//GEN-END:variables
}
