/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetpanneaupub;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import  java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AMEGNITO Brice
 */
public class panneaux extends javax.swing.JFrame {

    /**
     * Creates new form panneaux
     */
    public panneaux() {
        initComponents();
        Affiche();
    }
    public void Affiche(){
        try {
            String donnee []={"Identifiant","Localisation","Taille","Prix"};
            DefaultTableModel model=new DefaultTableModel(null,donnee);
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
            prst1=connect.prepareStatement("SELECT * FROM  panneau ");
            rsl=prst1.executeQuery();
            while(rsl.next()){
                Object ob[]={
                    rsl.getString("Id_panneau"),
                    rsl.getString("Localisation_panneau"),
                    rsl.getString("Taille"),
                    rsl.getString("Prix")
                };
                model.addRow(ob);
            }
            TablePan.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(panneaux.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     Connection connect ;
    PreparedStatement prst,prst1;
     ResultSet rsl;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtlocalisation = new javax.swing.JTextField();
        txtTaille = new javax.swing.JTextField();
        AjoutBtn = new javax.swing.JButton();
        ModifierBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPrix = new javax.swing.JTextField();
        SupprBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Localisation ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Taille");

        txtTaille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTailleActionPerformed(evt);
            }
        });
        txtTaille.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTailleKeyPressed(evt);
            }
        });

        AjoutBtn.setText("Ajouter");
        AjoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutBtnActionPerformed(evt);
            }
        });

        ModifierBtn.setText("Modifier");
        ModifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Prix");

        txtPrix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrixKeyPressed(evt);
            }
        });

        SupprBtn.setText("Supprimer");
        SupprBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENREGISTRMENT PANNEAU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(AjoutBtn)
                        .addGap(31, 31, 31)
                        .addComponent(ModifierBtn)
                        .addGap(18, 18, 18)
                        .addComponent(SupprBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrix, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txtlocalisation)
                            .addComponent(txtTaille, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(22, 22, 22))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtlocalisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupprBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablePan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTailleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTailleActionPerformed

    private void AjoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutBtnActionPerformed
            String reg_paternes= "^[a-zA-Z0-9]{1,25}$";
            Pattern patte = Pattern.compile(reg_paternes);
            Matcher match =patte.matcher(txtlocalisation.getText());
            String localisation = txtlocalisation.getText();
            String taille = txtTaille.getText();
            String prix = txtPrix.getText();
         if(localisation.equals("")||taille.equals("")||prix.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir Tous les champs");
        }else if(!match.matches()){
                JOptionPane.showMessageDialog(null, "Veuillez saisir un nom valide");
            
             }else{
         
        try {
            // TODO add your handling code here:
             
            
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
                prst1=connect.prepareStatement("SELECT * FROM  panneau WHERE Localisation_panneau=? ");
                prst1.setString(1, localisation);

                rsl=prst1.executeQuery();
                if(rsl.next()){
                    JOptionPane.showMessageDialog(this, "Ce panneau est déja! enrégistrer");
                }else{
                    try {

                        prst = connect.prepareStatement("INSERT INTO  panneau(Localisation_panneau	,Taille,Prix) VALUES(?,?,?)");
                        prst.setString(1, localisation);
                        prst.setString(2,taille);
                        prst.setString(3,prix);
                        prst.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Panneau ajouté!");
                        txtlocalisation.setText("");
                        txtTaille.setText("");
                        txtPrix.setText("");

                    } catch (SQLException ex) {
                        Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                    }                     }
                } catch (SQLException ex) {
                    Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
            }
            Affiche();
        }
    }//GEN-LAST:event_AjoutBtnActionPerformed

    private void ModifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBtnActionPerformed
        // TODO add your handling code here:
            String localisation = txtlocalisation.getText();
            String taille = txtTaille.getText();
            String prix = txtPrix.getText();
        if(localisation.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez Clicker l'élément à modifier");
        } else{
         DefaultTableModel mod =new DefaultTableModel();
        mod =(DefaultTableModel)TablePan.getModel();
        int select = TablePan.getSelectedRow();
        int id = Integer.parseInt(mod.getValueAt(select, 0).toString());
        
        
            // TODO add your handling code here:
            

            /*try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
                prst1=connect.prepareStatement("SELECT * FROM  panneau WHERE Localisation_panneau=?,Taille=?, Prix=?  ");
                prst1.setString(1, localisation);
                prst1.setString(2,taille);
                prst1.setString(3,prix);
                rsl=prst1.executeQuery();
                if(rsl.next()){
                    JOptionPane.showMessageDialog(this, "Ce panneau est déja! enrégistrer");
                }else{*/
       
                    try {

                        prst = connect.prepareStatement("UPDATE panneau SET Localisation_panneau=?, Taille=?, Prix=? WHERE Id_panneau =?");
                        prst.setString(1, localisation);
                        prst.setString(2,taille);
                        prst.setString(3,prix);
                        prst.setInt(4,id);
                        prst.executeUpdate();
                        JOptionPane.showMessageDialog(this, " Modifier!");
                        txtlocalisation.setText("");
                        txtTaille.setText("");
                        txtPrix.setText("");

                    } catch (SQLException ex) {
                        Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                    }                   
                /*}
                } catch (Exception e) {
                    Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, e);
                } */

            
            Affiche();
            AjoutBtn.setEnabled(true);
         }
    }//GEN-LAST:event_ModifierBtnActionPerformed

    private void TablePanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePanMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel mod =new DefaultTableModel();
        mod =(DefaultTableModel)TablePan.getModel();
        int select = TablePan.getSelectedRow();
        int id = Integer.parseInt(mod.getValueAt(select, 0).toString());
        txtlocalisation.setText(mod.getValueAt(select, 1).toString());
        txtTaille.setText(mod.getValueAt(select, 2).toString());
        txtPrix.setText(mod.getValueAt(select, 3).toString());
        AjoutBtn.setEnabled(false);
    }//GEN-LAST:event_TablePanMouseClicked

    private void SupprBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprBtnActionPerformed
        // TODO add your handling code here:
         String localisation = txtlocalisation.getText();
          if(localisation.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez Clicker l'élément à Supprimer");
        } else{
        DefaultTableModel mod =new DefaultTableModel();
        mod =(DefaultTableModel)TablePan.getModel();
        int select = TablePan.getSelectedRow();
        int id = Integer.parseInt(mod.getValueAt(select, 0).toString());
        
        
            // TODO add your handling code here:
            /*String localisation = txtlocalisation.getText();
            String taille = txtTaille.getText();
            String prix = txtPrix.getText();*/
        
         try {

                        prst = connect.prepareStatement("DELETE FROM panneau  WHERE Id_panneau =?");
                        prst.setInt(1,id);
                        prst.executeUpdate();
                        JOptionPane.showMessageDialog(this, " Supprimer!");
                        txtlocalisation.setText("");
                        txtTaille.setText("");
                        txtPrix.setText("");

                    } catch (SQLException ex) {
                        Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                    }                   
                /*}
                } catch (Exception e) {
                    Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, e);
                } */

            
            Affiche();
            AjoutBtn.setEnabled(true);
          }
    }//GEN-LAST:event_SupprBtnActionPerformed

    private void txtTailleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTailleKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            txtTaille.setEditable(false);
        }else{
             txtTaille.setEditable(true);
        }
    }//GEN-LAST:event_txtTailleKeyPressed

    private void txtPrixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrixKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(Character.isLetter(c)){
            txtPrix.setEditable(false);
        }else{
            txtPrix.setEditable(true);
        }
    }//GEN-LAST:event_txtPrixKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panneaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panneaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panneaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panneaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new panneaux().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutBtn;
    private javax.swing.JButton ModifierBtn;
    private javax.swing.JButton SupprBtn;
    private javax.swing.JTable TablePan;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtTaille;
    private javax.swing.JTextField txtlocalisation;
    // End of variables declaration//GEN-END:variables
}
