/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetpanneaupub;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import  java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author AMEGNITO Brice
 */
public class Utilisateur extends javax.swing.JFrame {

    /**
     * Creates new form Utilisateur
     */
    public Utilisateur() {
        initComponents();
        AfficheUTILISATEUR();
    }
    
    public void AfficheUTILISATEUR(){
        try {
            String donnee []={"ID","Nom","Mot de Passe","Téléphone","Option"};
            DefaultTableModel model=new DefaultTableModel(null,donnee);
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
            prst1=connect.prepareStatement("SELECT * FROM   admin ");
            rsl=prst1.executeQuery();
            while(rsl.next()){
                Object ob[]={
                    rsl.getString("id_Admin"),//
                    rsl.getString("Nom_Admin"),
                    rsl.getString("PasseWrdAdmin"),
                    rsl.getString("telephone_Admin"),
                    rsl.getString("OptionPersonnel")
                };
                model.addRow(ob);
            }
            TableUser.setModel(model);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(panneaux.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    Connection connect ;
    PreparedStatement prst,prst1;
     ResultSet rsl;
    
    public void conect(){
       try {
           
			Class.forName("com.mysql.cj.jdbc.Driver");
			connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
     
	


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtUserPass = new javax.swing.JTextField();
        AjoutBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtUserTel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CbxOption = new javax.swing.JComboBox<>();
        ModifierBtn = new javax.swing.JButton();
        SupprBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Nom utilisateur");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Mot de passe");

        txtUserPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserPassActionPerformed(evt);
            }
        });

        AjoutBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AjoutBtn.setText("Ajouter");
        AjoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Téléphone");

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENREGISTRMENT UTILISATEUR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Option");

        CbxOption.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CbxOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personnel", "Administrateur" }));

        ModifierBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ModifierBtn.setText("Modifier");
        ModifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifierBtnActionPerformed(evt);
            }
        });

        SupprBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SupprBtn.setText("Supprimer");
        SupprBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupprBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(CbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(AjoutBtn)
                        .addGap(40, 40, 40)
                        .addComponent(ModifierBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SupprBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserPass)
                            .addComponent(txtUserTel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addComponent(txtUserTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(CbxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AjoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SupprBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom ", "Mot de Passe ", "Téléphone", "Option"
            }
        ));
        TableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AjoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutBtnActionPerformed
                 try {                                         
                     // TODO add your handling code here:
                     String Username = txtUsername.getText();
                     String UserPass = txtUserPass.getText();
                     String UserTel = txtUserTel.getText();
                     String UserOption =  CbxOption.getSelectedItem().toString();
                     
                     
                    
                     if(Username.equals("")||UserPass.equals("")||UserTel.equals("")){
                         
                        JOptionPane.showMessageDialog(null, "Veuillez remplir Tous les champs");

                         
                     }else{
                         try {
                          Class.forName("com.mysql.cj.jdbc.Driver");
                         connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/panneau_pub","root","");
                          prst1=connect.prepareStatement("SELECT * FROM admin WHERE Nom_Admin=? ");
                     prst1.setString(1, UserTel);
                     
                     rsl=prst1.executeQuery();
                     if(rsl.next()){
                         JOptionPane.showMessageDialog(this, "Utilisateur existe déja!");
                     }else{
                    try {
                         
                         
                         prst = connect.prepareStatement("INSERT INTO admin(Nom_Admin,PasseWrdAdmin,telephone_Admin,OptionPersonnel) VALUES(?,?,?,?)");
                         prst.setString(1, Username);
                         prst.setString(2,UserPass);
                         prst.setString(3,UserTel);
                         prst.setString(4,UserOption);
                         prst.executeUpdate();
                         JOptionPane.showMessageDialog(this, "Utilisateur ajouté!");
                         txtUsername.setText("");
                         txtUserPass.setText("");
                         txtUserTel.setText("");
                         
                     } catch (SQLException ex) {
                         Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                     }                     }
                     } catch (SQLException ex) {
                         Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                     }
                     }
                     
                 } catch (ClassNotFoundException ex) {
            Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
	  AfficheUTILISATEUR();
	
    }//GEN-LAST:event_AjoutBtnActionPerformed

    private void txtUserPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserPassActionPerformed

    private void ModifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifierBtnActionPerformed
        // TODO add your handling code here:
        String Username = txtUsername.getText();
        String UserPass = txtUserPass.getText();
        String UserTel = txtUserTel.getText();
        String UserOption =  CbxOption.getSelectedItem().toString();
        if(Username.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez Clicker l'élément à modifier");
        } else{
            DefaultTableModel mod =new DefaultTableModel();
            mod =(DefaultTableModel)TableUser.getModel();
            int select = TableUser.getSelectedRow();
            int id = Integer.parseInt(mod.getValueAt(select, 0).toString());

                    try {

                        prst = connect.prepareStatement("UPDATE admin SET Nom_Admin=?, PasseWrdAdmin=?, telephone_Admin=? ,OptionPersonnel=? WHERE id_Admin =?");
                        prst.setString(1, Username);
                        prst.setString(2,UserPass);
                        prst.setString(3,UserTel);
                        prst.setString(4,UserOption);
                        prst.setInt(5,id);
                        prst.executeUpdate();
                        JOptionPane.showMessageDialog(this, " Modifier!");
                        txtUsername.setText("");
                        txtUserPass.setText("");
                        txtUserTel.setText("");

                    } catch (SQLException ex) {
                        Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    /*}
            } catch (Exception e) {
                Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, e);
            } */

            AfficheUTILISATEUR();
            AjoutBtn.setEnabled(true);
        }
    }//GEN-LAST:event_ModifierBtnActionPerformed

    private void TableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseClicked
        // TODO add your handling code here:
        DefaultTableModel mod =new DefaultTableModel();
        mod =(DefaultTableModel)TableUser.getModel();
        int select = TableUser.getSelectedRow();
        int id = Integer.parseInt(mod.getValueAt(select, 0).toString());
        txtUsername.setText(mod.getValueAt(select, 1).toString());
        txtUserPass.setText(mod.getValueAt(select, 2).toString());
        txtUserTel.setText(mod.getValueAt(select, 3).toString());
        AjoutBtn.setEnabled(false);
    }//GEN-LAST:event_TableUserMouseClicked

    private void SupprBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupprBtnActionPerformed
        // TODO add your handling code here:
        String Username = txtUsername.getText();
        if(Username.equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez Clicker l'élément à Supprimer");
        } else{
            DefaultTableModel mod =new DefaultTableModel();
            mod =(DefaultTableModel)TableUser.getModel();
            int select = TableUser.getSelectedRow();
            int id = Integer.parseInt(mod.getValueAt(select, 0).toString());

            // TODO add your handling code here:
            /*String localisation = txtlocalisation.getText();
            String taille = txtTaille.getText();
            String prix = txtPrix.getText();*/

            try {

                prst = connect.prepareStatement("DELETE FROM admin  WHERE id_Admin =?");
                prst.setInt(1,id);
                prst.executeUpdate();
                JOptionPane.showMessageDialog(this, " Supprimer!");
                txtUsername.setText("");
                txtUserPass.setText("");
                txtUserTel.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
            }
            /*}
        } catch (Exception e) {
            Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, e);
        } */

        AfficheUTILISATEUR();
        AjoutBtn.setEnabled(true);
        }
    }//GEN-LAST:event_SupprBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutBtn;
    private javax.swing.JComboBox<String> CbxOption;
    private javax.swing.JButton ModifierBtn;
    private javax.swing.JButton SupprBtn;
    private javax.swing.JTable TableUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtUserPass;
    private javax.swing.JTextField txtUserTel;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
